version: "3"
services:
    redis:
      container_name: redis
      build: .
      ports:
       - "6379:6379"
      volumes:
        - .:/data
      command: redis-server /data/redis.conf
      network_mode: bridge
      privileged: true
